// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBkAl41El3f6QySf1xKlsF3tNEh_Q_KQw',
    appId: '1:575279211899:web:873c8b2ac7e6b6bcbe89de',
    messagingSenderId: '575279211899',
    projectId: 'carpoolingapp-4e369',
    authDomain: 'carpoolingapp-4e369.firebaseapp.com',
    storageBucket: 'carpoolingapp-4e369.appspot.com',
    measurementId: 'G-670SPBDKWM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDarLekE60nOekNMohUcZl5tXA-o0gOGTo',
    appId: '1:575279211899:android:e9081ab383225a02be89de',
    messagingSenderId: '575279211899',
    projectId: 'carpoolingapp-4e369',
    storageBucket: 'carpoolingapp-4e369.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCyKD2el8A53K6nAtdG0xieRhtqUawUgE',
    appId: '1:575279211899:ios:3bfa1871d89533aebe89de',
    messagingSenderId: '575279211899',
    projectId: 'carpoolingapp-4e369',
    storageBucket: 'carpoolingapp-4e369.appspot.com',
    iosBundleId: 'com.example.carpoolingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCyKD2el8A53K6nAtdG0xieRhtqUawUgE',
    appId: '1:575279211899:ios:84ea76ef06452386be89de',
    messagingSenderId: '575279211899',
    projectId: 'carpoolingapp-4e369',
    storageBucket: 'carpoolingapp-4e369.appspot.com',
    iosBundleId: 'com.example.carpoolingApp.RunnerTests',
  );
}
